//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_BASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GUITARE
    {
        public int idGuitare { get; set; }
        public string nom { get; set; }
        public string corps { get; set; }
        public string manche { get; set; }
        public string touche { get; set; }
        public string micro { get; set; }
        public string vibrato { get; set; }
        public string bridge { get; set; }
        public string centrale { get; set; }
        public string neck { get; set; }
        public int idBois_Corps { get; set; }
        public int idBois_Manche { get; set; }
        public int idBois_Touche { get; set; }
        public int idMicro { get; set; }
        public int idMicro_1 { get; set; }
        public Nullable<int> idMicro_2 { get; set; }
        public int idVibrato { get; set; }
        public Nullable<int> idClient { get; set; }
    
        public virtual C_BOIS Le_Bois_Corps { get; set; }
        public virtual C_BOIS Le_Bois_Manche { get; set; }
        public virtual C_BOIS Le_Bois_Touche { get; set; }
        public virtual C_CLIENT Le_Proprietaire { get; set; }
        public virtual C_MICRO Micro1 { get; set; }
        public virtual C_MICRO Micro2 { get; set; }
        public virtual C_MICRO Micro3 { get; set; }
        public virtual C_VIBRATO Le_Vibrato { get; set; }
    }
}
